accepted = ["Apache-2.0", "ISC", "MIT", "MPL-2.0"]
ignore-dev-dependencies = true
private = { ignore = true }
workarounds = [
    "rustls",
]

[ring]
accepted = ["OpenSSL"]

[ring.clarify]
license = "ISC AND MIT AND OpenSSL"

[[ring.clarify.files]]
path = 'LICENSE'
license = 'OpenSSL'
checksum = '76b39f9b371688eac9d8323f96ee80b3aef5ecbc2217f25377bd4e4a615296a9'

[alloc-no-stdlib]
accepted = ["BSD-3-Clause"]

[encoding_rs]
accepted = ["BSD-3-Clause"]

[instant]
accepted = ["BSD-3-Clause"]

[lol_html]
accepted = ["BSD-3-Clause"]

[alloc-stdlib]
accepted = ["BSD-3-Clause"]

[subtle]
accepted = ["BSD-3-Clause"]

[unicode-ident]
accepted = ["Unicode-DFS-2016"]

[brotli]
accepted = ["BSD-3-Clause"]

[webpki.clarify]
license = "ISC"

[[webpki.clarify.files]]
path = 'LICENSE'
license = 'ISC'
checksum = '5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a'

[rustls-webpki.clarify]
license = "ISC"

[[rustls-webpki.clarify.files]]
path = 'LICENSE'
license = 'ISC'
checksum = '5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a'

[typenum.clarify]
license = "MIT OR Apache-2.0"

[[typenum.clarify.files]]
path = 'LICENSE-APACHE'
license = 'Apache-2.0'
checksum = '516b24e051bf5630880ebbd55c40a25ce9552ebaf8970a53e8976eb70e522406'

[[typenum.clarify.files]]
path = 'LICENSE-MIT'
license = 'MIT'
checksum = 'a825bd853ab71619a4923d7b4311221427848070ff44d990da39b0b274c1683f'

[widestring.clarify]
license = "MIT OR Apache-2.0"

[[widestring.clarify.files]]
path = 'LICENSE'
license = 'MIT'
checksum = '36bb253818ac13761081556ff5c457d626da9df1eb4f56194d9ad3926c418a68'
