[package]
name = "searproxy"
version = "0.2.1"
edition = "2021"
license = "AGPL-3.0"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]
base64 = "=0.13.0"
bytes = "=1.1.0"
clap = { version = "=3.1.6", features = ["derive", "env"] }
fern = "=0.6.0"
futures-util = "=0.3.21"
hex = "=0.4.3"
hmac = "=0.12.1"
htmlentity = "=1.2.0"
log = "=0.4.14"
lol_html = "=0.3.1"
markup = "=0.12.5"
mime = "=0.3.16"
once_cell = "=1.10.0"
regex = "=1.5.5"
serde = { version = "=1.0.136", features = ["derive"] }
serde_qs = "=0.9.1"
thiserror = "=1.0.30"
url = "=2.2.2"

[dependencies.actix-web]
version = "=4.0.1"
default-features = false
features = ["compress-brotli", "compress-gzip", "compress-zstd", "macros"]

[dependencies.reqwest]
version = "=0.11.10"
default-features = false
features = ["brotli", "socks", "gzip", "deflate", "stream", "rustls-tls", "trust-dns"]

[dependencies.sha2]
version = "=0.10.2"
default-features = false
features = ["asm", "std"]

[build-dependencies]
base64 = "=0.13.0"
parcel_css = "=1.0.0-alpha.19"

[build-dependencies.sha2]
version = "=0.10.2"
default-features = false
features = ["std"]
