[package]
name = "searproxy"
version = "0.4.1"
edition = "2021"
license = "AGPL-3.0"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]
base64 = "=0.21.2"
bytes = "=1.4.0"
clap = { version = "=4.4.0", features = ["derive", "env"] }
fern = "=0.6.2"
futures-util = "=0.3.28"
hex = "=0.4.3"
hmac = "=0.12.1"
htmlentity = "=1.3.1"
log = "=0.4.20"
lol_html = "=1.1.1"
markup = "=0.13.1"
mime = "=0.3.17"
once_cell = "=1.18.0"
regex = "=1.9.4"
serde = { version = "=1.0.187", features = ["derive"] }
serde_qs = "=0.12.0"
thiserror = "=1.0.47"
url = "=2.4.0"

[dependencies.actix-web]
version = "=4.3.1"
default-features = false
features = ["compress-brotli", "compress-gzip", "compress-zstd", "macros"]

[dependencies.reqwest]
version = "=0.11.20"
default-features = false
features = ["brotli", "socks", "gzip", "deflate", "stream", "rustls-tls", "trust-dns"]

[target.'cfg(not(any(target_arch = "arm", target_arch = "armv7")))'.dependencies.sha2]
version = "=0.10.7"
default-features = false
features = ["asm", "std"]

[target.'cfg(any(target_arch = "arm", target_arch = "armv7"))'.dependencies.sha2]
version = "=0.10.7"
default-features = false
features = ["std"]

[build-dependencies]
base64 = "=0.21.2"
lightningcss = "=1.0.0-alpha.45"

[build-dependencies.sha2]
version = "=0.10.7"
default-features = false
features = ["std"]
