[package]
name = "searproxy"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
actix-web = { version = "4.0.0-rc.3", features = ["compress-brotli", "compress-gzip"] }
base64 = "0.13.0"
bytes = "1.1.0"
clap = { version = "3.0.12", features = ["derive", "env"] }
fern = "0.6.0"
futures-util = "0.3.21"
hex = "0.4.3"
hmac-sha256 = "1.1.1"
log = "0.4.14"
lol_html = "0.3.0"
mime = "0.3.16"
once_cell = "1.9.0"
regex = "1.5.4"
reqwest = { version = "0.11.9", features = ["brotli", "socks", "gzip", "deflate", "stream"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_qs = "0.8.5"
thiserror = "1.0.30"
url = "2.2.2"

[dependencies.tera]
default-features = false
version = "1.15.0"