[package]
name = "searproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.0.0-rc.3", features = ["compress-brotli", "compress-gzip"] }
async-recursion = "1.0.0"
base64 = "0.13.0"
bytes = "1.1.0"
clap = { version = "3.0.12", features = ["derive", "env"] }
cssparser = "0.29.2"
futures-util = "0.3.21"
hex = "0.4.3"
hmac-sha256 = "1.1.1"
lol_html = "0.3.0"
mime = "0.3.16"
minify-html = "0.8.0"
once_cell = "1.9.0"
regex = "1.5.4"
reqwest = { version = "0.11.9", features = ["brotli", "socks", "gzip", "deflate", "stream"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_qs = "0.8.5"
tera = "1.15.0"
thiserror = "1.0.30"
tracing = "0.1.29"
tracing-actix-web = "0.5.0-rc.3"
tracing-subscriber = "0.3.8"
url = "2.2.2"