[package]
name = "searproxy"
version = "0.2.28"
edition = "2021"
license = "AGPL-3.0"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]
base64 = "=0.21.0"
bytes = "=1.4.0"
clap = { version = "=4.1.8", features = ["derive", "env"] }
fern = "=0.6.1"
futures-util = "=0.3.26"
hex = "=0.4.3"
hmac = "=0.12.1"
htmlentity = "=1.2.0"
log = "=0.4.17"
lol_html = "=0.3.2"
markup = "=0.13.1"
mime = "=0.3.16"
once_cell = "=1.17.1"
regex = "=1.7.1"
serde = { version = "=1.0.152", features = ["derive"] }
serde_qs = "=0.11.0"
thiserror = "=1.0.38"
url = "=2.3.1"

[dependencies.actix-web]
version = "=4.3.0"
default-features = false
features = ["compress-brotli", "compress-gzip", "compress-zstd", "macros"]

[dependencies.reqwest]
version = "=0.11.14"
default-features = false
features = ["brotli", "socks", "gzip", "deflate", "stream", "rustls-tls", "trust-dns"]

[target.'cfg(not(any(target_arch = "arm", target_arch = "armv7")))'.dependencies.sha2]
version = "=0.10.6"
default-features = false
features = ["asm", "std"]

[target.'cfg(any(target_arch = "arm", target_arch = "armv7"))'.dependencies.sha2]
version = "=0.10.6"
default-features = false
features = ["std"]

[build-dependencies]
base64 = "=0.21.0"
lightningcss = "=1.0.0-alpha.40"

[build-dependencies.sha2]
version = "=0.10.6"
default-features = false
features = ["std"]
