[package]
name = "searproxy"
version = "0.2.24"
edition = "2021"
license = "AGPL-3.0"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]
base64 = "=0.13.1"
bytes = "=1.2.1"
clap = { version = "=4.0.18", features = ["derive", "env"] }
fern = "=0.6.1"
futures-util = "=0.3.25"
hex = "=0.4.3"
hmac = "=0.12.1"
htmlentity = "=1.2.0"
log = "=0.4.17"
lol_html = "=0.3.1"
markup = "=0.13.1"
mime = "=0.3.16"
once_cell = "=1.16.0"
regex = "=1.6.0"
serde = { version = "=1.0.147", features = ["derive"] }
serde_qs = "=0.10.1"
thiserror = "=1.0.37"
url = "=2.3.1"

[dependencies.actix-web]
version = "=4.2.1"
default-features = false
features = ["compress-brotli", "compress-gzip", "compress-zstd", "macros"]

[dependencies.reqwest]
version = "=0.11.12"
default-features = false
features = ["brotli", "socks", "gzip", "deflate", "stream", "rustls-tls", "trust-dns"]

[target.'cfg(not(any(target_arch = "arm", target_arch = "armv7")))'.dependencies.sha2]
version = "=0.10.6"
default-features = false
features = ["asm", "std"]

[target.'cfg(any(target_arch = "arm", target_arch = "armv7"))'.dependencies.sha2]
version = "=0.10.6"
default-features = false
features = ["std"]

[build-dependencies]
base64 = "=0.13.1"
lightningcss = "=1.0.0-alpha.35"

[build-dependencies.sha2]
version = "=0.10.6"
default-features = false
features = ["std"]
