name: cargo-deny

on:
  push:
    branches: "*"
    paths:
      - 'Cargo.toml'
      - 'deny.toml'
      - '.github/workflows/cargo-deny.yml'

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
