name: GitHub pages

on:
  push:
    branches:
      - main
    paths:
      - "public/**"
      - ".github/workflows/gh-pages.yml"

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to GH pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: public
          clean: true
