name: Cargo licensing

on:
  push:
    branches:
      - main
    paths:
      - "Cargo.toml"
      - "licensing/about.hbs"
      - "licensing/about.toml"
      - ".github/workflows/licensing.yml"

permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

env:
  CARGO_TERM_COLOR: always

jobs:
  licensing:
    name: Generate third party license overview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Install "cargo-about"
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --locked cargo-about
      - name: Create "docs" directory (if necessary)
        run: |
          if [[ ! -d docs ]]; then
            mkdir docs
          fi
      - name: Generate third party license overview
        run: cargo-about generate -o docs/licenses.html licensing/about.hbs -c licensing/about.toml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update third party license overview
          title: Update third party licenses
          body: |
            This is an auto-generated PR for third party license changes.

            > Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: auto-generated-third-party-license-overview
          branch-suffix: short-commit-hash
          add-paths: docs/licenses.html
          labels: license
          draft: false
